apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources: 
- namespace.yaml

helmGlobals: 
  chartHome: '../manifests'

helmCharts:
  - name: 'kube-prometheus-stack'
    releaseName: prometheus-stack
    namespace: monitoring
    # includeCRDs: true
    valuesInLine:
      crds:
        enabled: true
      service:
        type: 'NodePort'